name: Update LED Ticker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-ticker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout WorkFlowRepo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        working-directory: docs/ticker-bot
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Install Python dependencies
        run: pip install requests

      - name: Fetch GitHub traffic stats
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: python docs/ticker-bot/fetch_stats.py

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libxshmfence1 \
            libxcomposite1 \
            libxrandr2 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libgbm1

      - name: Generate banner
        run: node docs/ticker-bot/generate_banner.js

      - name: Set up PAT-based push auth
        run: |
          git config --global user.name "gremlin-bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.PAT_GITHUB }}@github.com/statikfintechllc/WorkFlowRepo.git

      - name: Commit and push banner
        run: |
          git add docs/ticker-bot/stats.json docs/ticker-bot/ticker.gif
          git diff --cached --quiet || git commit -m "Update traffic data and Banner"
          git pull --rebase
          git push
